### ISSUE TITLE
Unexpected error when liking users

### ISSUE THREAD

**Issue by WulfieWolf** [howlrapp/howlr-app#3] opened 2020-11-23 14:32 UTC
When I like users, sometimes there is only a small flash of an "unexpected error" message and the like is not successful. 
Just some users are affected. But if they are affected, it seems to be permanently. 
Deleting cache and reinstalling the app was not successful.

**Comment by howlrapp** [comment] 2020-11-25 09:04
Hello! I couldn't reproduce your issue yet. I suspect that it may come from duplicated likes in some way or another and updated the backend to accept Like requests even if a Like request already exists (it'll just be a noop in that case). Let me know if it makes things better, in any case I'm keeping this ticket open until we figure out more.

Thanks for reporting this issue, have a great day!

**Comment by GamingWithJanko** [comment] 2020-12-13 22:01
I exceeded the 100 like listing, but I can't make screenshots, therefore no recording.
It greys out the button for a solid 5 secs or so, but it then just goes blue again, without the button saying "unlike".

Long story short, I'm experiencing pretty much the same problem.

**Comment by Alexbeari18** [comment] 2020-12-15 02:56
having the exact same problem getting very frustrated, please fix

**Comment by p0wertiger** [comment] 2020-12-23 00:45
Problem with likes here as well. Touching Like causes it to gray out for a few seconds but then it goes back to Like again, state doesn't change, no error, no popup, nothing. Some old likes that I had toggled in the past are not showing anymore, but some do. The same from user list and likes list.

**Comment by Alexbeari18** [comment] 2020-12-23 01:20
does anyone even know how to get in touch with the developers? I can't find any info on how to do it

**Comment by BlueWoozle** [comment] 2021-04-22 12:30
Having the exact same issue. 
When I press like on certain user profiles, the like button will turn grey for a few seconds, then revert without the like being applied. 
Once this happens with a user, it seems that the user permanently cannot be liked from my profile.

**Comment by howlrapp** [comment] 2021-07-24 22:44
We worked on this issue and it should hopefully be fixed now. Thanks for reporting it and feel free to reopen this issue if you're still experiencing problems!

**Closed as completed by howlrapp** 2021-07-24 22:44 UTC

**Comment by valzargaming** [comment] 2021-08-05 12:33
I can confirm this issue is still happening. I experienced this first recently before starting to receive "Not Authorized". I suspected this was related to an expired token, so I cleared my data and cache and logged back in, but the error changed to "Unexpected error". This can happen when liking a profile or sending a message request for any of the 4 reasons available.

I tested it again this morning and it seems as though I receive an unexpected error trying to send any new likes.

**Comment by valzargaming** [comment] 2021-08-06 13:01
I tried to replicate this again later in the day yesterday after reinstalling the app a second time,  but everything seems to be working now. There seems to be an arbitrary ratelimit I was hitting at the same time. I think the real solution is to make the error messages clearer, and preferably provide information about why there is a ratelimit in the first place and when it will expire.

**Comment by howlrapp** [comment] 2021-08-06 14:03
Hello @valzargaming! Yes we experimented with rate limiting recently and it definitely needed some tweaking, it is now less susceptible to target legitimate users. We also changed the error message so that users know that their account is temporarily limited. 

Thank you for your reporting this issue!
